# Generated by Django 5.1.2 on 2026-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaevaluable',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareagrupo',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareaindividual',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
